In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../Camp_Election.Oracle/Correlates of State Policy/correlates2-6.csv')
df = df[df['year'] > 1975]
df

C:\Users\jelle\AppData\Local\Temp\ipykernel_8544\306222963.py:1: DtypeWarning: Columns (487,491,497,499,502,504,508,511,518,523,525,530,1496,1871,2106,2269,2270,2271,2272,2273,2274,2275,2276) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../Camp_Election.Oracle/Correlates of State Policy/correlates2-6.csv')

,st,stateno,state,state_fips,state_icpsr,year,popdensity,popfemale,pctpopfemale,popmale,...,num_enacted_laws,gunhomicides,femmurdersfamilybygun,mass_shooting_num,numregdvgunlawenact,intropot,signedpot,introcat1pot,introcat2pot,introcat3pot
76,AK,2.0,Alaska,2,81,1976,0.688202,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,AK,2.0,Alaska,2,81,1977,0.695225,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,AK,2.0,Alaska,2,81,1978,0.704003,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,AK,2.0,Alaska,2,81,1979,0.705759,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,AK,2.0,Alaska,2,81,1980,0.702247,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6166,WY,50.0,Wyoming,56,68,2016,NaN,NaN,49.1,NaN,...,0.0,5.0,2.0,0.0,2.0,1.0,0.0,0.0,1.0,0.0
6167,WY,50.0,Wyoming,56,68,2017,NaN,NaN,48.9,NaN,...,0.0,NaN,NaN,0.0,4.0,NaN,NaN,NaN,NaN,NaN
6168,WY,50.0,Wyoming,56,68,2018,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6169,WY,50.0,Wyoming,56,68,2019,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6170,WY,50.0,Wyoming,56,68,2020,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
missing_percentage = df.isna().mean() * 100
#print(missing_percentage)
columns_to_keep = missing_percentage[missing_percentage <= 3].index
print(columns_to_keep)
df_filtered = df[columns_to_keep]
df_filtered

Index(['st', 'stateno', 'state', 'state_fips', 'state_icpsr', 'year',
       'incomepcap', 'poptotal', 'taxes', 'legcount_sen_w', 'legcount_sen_b',
       'legcount_sen_n', 'legcount_sen_e', 'legcount_sen_l', 'legcount_sen_ln',
       'legcount_sen_el', 'legcount_sen_c', 'legcount_sen_bl',
       'legcount_sen_s', 'legcount_sen_p', 'legcount_sen_ep',
       'legcount_sen_elp', 'legcount_sen_bn', 'legcount_sen_m',
       'legcount_sen_bs'],
      dtype='object')

,st,stateno,state,state_fips,state_icpsr,year,incomepcap,poptotal,taxes,legcount_sen_w,...,legcount_sen_el,legcount_sen_c,legcount_sen_bl,legcount_sen_s,legcount_sen_p,legcount_sen_ep,legcount_sen_elp,legcount_sen_bn,legcount_sen_m,legcount_sen_bs
76,AK,2.0,Alaska,2,81,1976,12109.0,400969.0,598806.0,18.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
77,AK,2.0,Alaska,2,81,1977,12388.0,403436.0,773474.0,18.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78,AK,2.0,Alaska,2,81,1978,12495.0,404766.0,563485.0,18.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
79,AK,2.0,Alaska,2,81,1979,13199.0,402753.0,816710.0,18.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
80,AK,2.0,Alaska,2,81,1980,14975.0,401851.0,1437607.0,18.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6166,WY,50.0,Wyoming,56,68,2016,54073.0,585501.0,1913607.0,29.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6167,WY,50.0,Wyoming,56,68,2017,56421.0,579315.0,1649550.0,29.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6168,WY,50.0,Wyoming,56,68,2018,60537.0,577601.0,1837401.0,29.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6169,WY,50.0,Wyoming,56,68,2019,62044.0,578759.0,2110704.0,28.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6170,WY,50.0,Wyoming,56,68,2020,NaN,NaN,NaN,28.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
df_income = df_filtered[['state', 'year', 'incomepcap']]
df_income[df_income['incomepcap'].isna()]

                     state  year  incomepcap
120                 Alaska  2020         NaN
241                Alabama  2020         NaN
362               Arkansas  2020         NaN
483                Arizona  2020         NaN
604             California  2020         NaN
725               Colorado  2020         NaN
846            Connecticut  2020         NaN
967   District of Columbia  2020         NaN
1088              Delaware  2020         NaN
1209               Florida  2020         NaN
1330               Georgia  2020         NaN
1451                Hawaii  2020         NaN
1572                  Iowa  2020         NaN
1693                 Idaho  2020         NaN
1814              Illinois  2020         NaN
1935               Indiana  2020         NaN
2056                Kansas  2020         NaN
2177              Kentucky  2020         NaN
2298             Louisiana  2020         NaN
2419         Massachusetts  2020         NaN
2540              Maryland  2020         NaN
2661                 Maine  2020         NaN
2782              Michigan  2020         NaN
2903             Minnesota  2020         NaN
3024              Missouri  2020         NaN
3145           Mississippi  2020         NaN
3266               Montana  2020         NaN
3387        North Carolina  2020         NaN
3508          North Dakota  2020         NaN
3629              Nebraska  2020         NaN
3750         New Hampshire  2020         NaN
3871            New Jersey  2020         NaN
3992            New Mexico  2020         NaN
4113                Nevada  2020         NaN
4234              New York  2020         NaN
4355                  Ohio  2020         NaN
4476              Oklahoma  2020         NaN
4597                Oregon  2020         NaN
4718          Pennsylvania  2020         NaN
4839          Rhode Island  2020         NaN
4960        South Carolina  2020         NaN
5081          South Dakota  2020         NaN
5202             Tennessee  2020         NaN
5323                 Texas  2020         NaN
5444                  Utah  2020         NaN
5565              Virginia  2020         NaN
5686               Vermont  2020         NaN
5807            Washington  2020         NaN
5928             Wisconsin  2020         NaN
6049         West Virginia  2020         NaN
6170               Wyoming  2020         NaN

In [ ]:
df_income.to_csv('income_state_year.csv')